name: Docker build image on release

# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set repo name lowercase
        id: repo
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.lowercase }}:latest

  trigger_deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Repository Dispatch
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: cybermouflons
          repo: ccsc-deployment-2025
          event_type: workflow_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
